spring:
  servlet:
    multipart:
      location: /Users/alex/IdeaProjects/PrecipitationForecast/tmpFile
logging:
  config: classpath:log4j2_dev.xml
table:
  location: /Users/alex/IdeaProjects/PrecipitationForecast/tmpFile/