server:
  port: 9999
  servlet:
    context-path: /rain
spring:
  servlet:
    multipart:
      enabled: true
      location: /root/java/tmp
      file-size-threshold: 0
      max-file-size: 200MB
      max-request-size: 200MB